{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mao.asm",
    "module": "asm_test_plugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "asm_test_plugin-1.0.1.jar",
          "url": "asm_test_plugin-1.0.1.jar",
          "size": 15979,
          "sha512": "c12e7802ec0a3db123362d2f26d31b6de6e2296d70a85a3c5372ede296eb40bd8320f89a63b61259955e686840439f4fd11b3e05a6ab3b5bf855af51bb738585",
          "sha256": "509ba04373d7b1578006f2c44c9afed4b5a3a1ae9c93003cdfcc72aa2649d1bb",
          "sha1": "383c7c0c1e3a0834bb784fa11e0cb92841bf3bda",
          "md5": "b023ce042cf5649402d8d6b06b5c160f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_test_plugin-1.0.1.jar",
          "url": "asm_test_plugin-1.0.1.jar",
          "size": 15979,
          "sha512": "c12e7802ec0a3db123362d2f26d31b6de6e2296d70a85a3c5372ede296eb40bd8320f89a63b61259955e686840439f4fd11b3e05a6ab3b5bf855af51bb738585",
          "sha256": "509ba04373d7b1578006f2c44c9afed4b5a3a1ae9c93003cdfcc72aa2649d1bb",
          "sha1": "383c7c0c1e3a0834bb784fa11e0cb92841bf3bda",
          "md5": "b023ce042cf5649402d8d6b06b5c160f"
        }
      ]
    }
  ]
}
